### ISSUE TITLE
COMException: Unable to add file. A file with that name already exists.

### ISSUE THREAD

**Issue by RudeySH** [NeVeSpl/NTypewriter#31]
I attempted to change the output folder like so:

```
filePath =  "Folder/" | String.Append class.BareName | String.Append ".ts"
Save output filePath
```

This gives me the following error:

```
INFO: Updating VisualStudio solution
ERROR: System.Runtime.InteropServices.COMException (0x80040400): Unable to add 'ClassModel.ts'. A file with that name already exists.
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at NTypewriter.EditorForVisualStudio.Editor.SolutionItemsManager.Update(IEnumerable`1 outputFiles)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<>c__DisplayClass11_0.<RenderTemplateCommand_OnExecuted>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<RenderTemplateCommand_OnExecuted>d__11.MoveNext()
```

It's worth noting that the files are being generated in the correct folder, but not included in the project (not added to the .csproj file). I tried removing the folder, but when rendering the template I get the "already exists" error again.

I tried changing `"Folder/"` to `"/Folder/"`, but that gave me a different error:

```
INFO: Updating VisualStudio solution
ERROR: System.Runtime.InteropServices.COMException (0x80004005): Cannot add a link to the file ClassModel.ts. There is already a file of the same name in this folder.
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at NTypewriter.EditorForVisualStudio.Editor.SolutionItemsManager.Update(IEnumerable`1 outputFiles)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<>c__DisplayClass11_0.<RenderTemplateCommand_OnExecuted>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<RenderTemplateCommand_OnExecuted>d__11.MoveNext()
```

What am I doing wrong? This seems like a bug.

**Comment by NeVeSpl** [comment]
VS is very picky about adding files to the solution. I would appreciate if you could upload the project with reproducible error.

**Comment by RudeySH** [comment]
Here you go: https://github.com/RudeySH/NTypewriterSampleClassLibrary

This uses the legacy project system. I haven't tested yet of I'm getting the same error in the newer SDK-style project system.
