### ISSUE TITLE
IType.Namespace throws an exception when using string[]

### ISSUE THREAD

**Issue by RudeySH** [NeVeSpl/NTypewriter#5]
When using a model with a `string[]` property:
```
public class ClassModel
{
    public string[] Foo { get; set; }
}
```

And using a template that uses `{{ property.Type.Namespace }}`:

```
module App {
    export class {{ class.Name }} {
            {{- for property in class.Properties | Symbols.ThatArePublic }}
        public {{ property.Name | String.ToCamelCase }}: {{ property.Type | Type.ToTypeScriptType }}; //{{ property.Type.Namespace }}
            {{- end }}
    }
}
    {{- end
        filePath =  class.BareName | String.Append ".ts"
        Save output filePath
    end }}
```

I get the following exception:

> INFO: Rendering template
ERROR: <input>(6,108) Unexpected exception while accessing target expression: Exception has been thrown by the target of an invocation.
ERROR: System.Exception: Rendering template failed
   at NTypewriter.EditorForVisualStudio.CoreDomain.TemplateRenderer.<RenderTemplate>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NTypewriter.EditorForVisualStudio.CoreDomain.TemplateRenderer.<RenderAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<RenderTemplateCommand_OnExecuted>d__11.MoveNext()

**Comment by NeVeSpl** [comment]
It appears that an array does not have a namespace. Fixed in 0.0.5

**Comment by RudeySH** [comment]
Thanks! When will the new version be released?

**Comment by NeVeSpl** [comment]
It was released yesterday, but apparently, something went wrong after uploading on the marketplace. I have republished it, and now should be available.
