### ISSUE TITLE
the variable or function 'array' was not found

### ISSUE THREAD

**Issue by gregveres** [NeVeSpl/NTypewriter#9]
I am trying to use Scriban's builtin array functions and I get this error:

```
09:43:29.012 INFO: Rendering template
09:43:29.014 ERROR: <input>(6,11) The variable or function `array` was not found
09:43:29.014 ERROR: System.Exception: Rendering template failed
   at NTypewriter.EditorForVisualStudio.CoreDomain.TemplateRenderer.<RenderTemplate>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NTypewriter.EditorForVisualStudio.CoreDomain.TemplateRenderer.<RenderAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NTypewriter.EditorForVisualStudio.NTypewriterEditorForVisualStudioPackage.<RenderTemplateCommand_OnExecuted>d__11.MoveNext()
```

Are the builtins not available? 

And if not, do you have a suggestion for how to join two arrays of classes together? I have a situation where I have two different attributes that are used in the code base to trigger conversion to Typescript:
ExportToTypescript
ExportToTypescriptWithKnockout

For this .nt file, I need to process both of these classes the same way, so I figured I would create two arrays, concatenate them and then process the resulting list like this:

```
{{- 
# gather the classes with ExportToTypescript and ExportToTypescriptWithKnockout.
# I have to gather them into one array that I can then iterate over
normal = data.Classes | Symbols.ThatHaveAttribute "ExportToTypescript"
knockout = data.Classes | Symbols.ThatHaveAttribute "ExportToTypescriptWithKnockout"
classes = array.concat normal knockout
Capture output 
classes
end
Save output "index.txt"
}}
```

**Comment by gregveres** [comment]
Ah, I see that you remapped them from array in Scriban to Array in your language. Got it.
https://github.com/NeVeSpl/NTypewriter/blob/master/Documentation/BuiltInFunctions.md#Add
